spring.application.name=BusManagement

spring.jpa.hibernate.ddl-auto=create 
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/busmanagement
spring.datasource.username=root
spring.datasource.password=giangmysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: false


#config spring security
spring.security.user.name=a
spring.security.user.password=a
# Cách này sẽ vô hiệu hóa hoàn toàn security (tùy version Spring Boot)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

